parameters:
  kwattro_markdown.extensions_config: %kwattro_markdown.extensions_config%

services:
  kwattro_markdown.twig_filter:
    class: %kwattro_markdown.twig_extension%
    arguments: [@kwattro_markdown]
    tags:
      - { name: twig.extension }
  
  kwattro_markdown:
    class: Kwattro\MarkdownBundle\Markdown\KwattroMarkdown
    arguments: [%kwattro_markdown.extensions_config%, %kwattro_markdown.renderer%]
